
AWSTemplateFormatVersion: 2010-09-09
Description:  Cloudformation template to create the DEV VPC and 12 subnets. Designed to skip ahead to this point in the course. When applying this template you will be ready to complete the DEMO lesson Configuring A4l public subnets and Jumpbox. 
Metadata:
  LICENSE: Apache License Version 2.0
Resources:
  #DevVPC
  DEVVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.20.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: dev-vpc
  # QaVPC
  QAVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.21.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: qa-vpc
  # ProdVPC
  PRODVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.22.0.0/16
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: prod-vpc
  
  # DEV Subnets
  SubnetFIMA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref DEVVPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: 10.20.0.0/20
      Tags:
        - Key: Name
          Value: sn-fim-A
  SubnetFIMB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref DEVVPC
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      CidrBlock: 10.20.64.0/20
      Tags:
        - Key: Name
          Value: sn-fim-B
  SubnetFIMC:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref DEVVPC
      AvailabilityZone: !Select [ 2, !GetAZs '' ]
      CidrBlock: 10.20.128.0/20
      Tags:
        - Key: Name
          Value: sn-fim-C
  SubnetSIEMA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref DEVVPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: 10.20.16.0/20
      Tags:
        - Key: Name
          Value: sn-siem-A
  SubnetSIEMB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref DEVVPC
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      CidrBlock: 10.20.80.0/20
      Tags:
        - Key: Name
          Value: sn-siem-B
  SubnetSIEMC:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref DEVVPC
      AvailabilityZone: !Select [ 2, !GetAZs '' ]
      CidrBlock: 10.20.144.0/20
      Tags:
        - Key: Name
          Value: sn-siem-C
  SubnetNFTAA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref DEVVPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: 10.20.32.0/20
      Tags:
        - Key: Name
          Value: sn-nfta-A
  SubnetNFTAB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref DEVVPC
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      CidrBlock: 10.20.96.0/20
      Tags:
        - Key: Name
          Value: sn-nfta-B
  SubnetNFTAC:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref DEVVPC
      AvailabilityZone: !Select [ 2, !GetAZs '' ]
      CidrBlock: 10.20.160.0/20
      Tags:
        - Key: Name
          Value: sn-nfta-C
  SubnetDMZA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref DEVVPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: 10.20.48.0/20
      Tags:
        - Key: Name
          Value: sn-dmz-A
  SubnetDMZB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref DEVVPC
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      CidrBlock: 10.20.112.0/20
      Tags:
        - Key: Name
          Value: sn-dmz-B
  SubnetDMZC:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref DEVVPC
      AvailabilityZone: !Select [ 2, !GetAZs '' ]
      CidrBlock: 10.20.176.0/20
      Tags:
        - Key: Name
          Value: sn-dmz-C
  
  # QA Subnets
  SubnetFIMA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref QAVPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: 10.21.0.0/20
      Tags:
        - Key: Name
          Value: sn-fim-A
  SubnetFIMB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref QAVPC
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      CidrBlock: 10.21.64.0/20
      Tags:
        - Key: Name
          Value: sn-fim-B
  SubnetFIMC:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref QAVPC
      AvailabilityZone: !Select [ 2, !GetAZs '' ]
      CidrBlock: 10.21.128.0/20
      Tags:
        - Key: Name
          Value: sn-fim-C
  SubnetSIEMA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref QAVPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: 10.21.16.0/20
      Tags:
        - Key: Name
          Value: sn-siem-A
  SubnetSIEMB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref QAVPC
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      CidrBlock: 10.21.80.0/20
      Tags:
        - Key: Name
          Value: sn-siem-B
  SubnetSIEMC:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref QAVPC
      AvailabilityZone: !Select [ 2, !GetAZs '' ]
      CidrBlock: 10.21.144.0/20
      Tags:
        - Key: Name
          Value: sn-siem-C
  SubnetNFTAA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref QAVPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: 10.21.32.0/20
      Tags:
        - Key: Name
          Value: sn-nfta-A
  SubnetNFTAB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref QAVPC
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      CidrBlock: 10.21.96.0/20
      Tags:
        - Key: Name
          Value: sn-nfta-B
  SubnetNFTAC:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref QAVPC
      AvailabilityZone: !Select [ 2, !GetAZs '' ]
      CidrBlock: 10.21.160.0/20
      Tags:
        - Key: Name
          Value: sn-nfta-C
  SubnetDMZA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref QAVPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: 10.21.48.0/20
      Tags:
        - Key: Name
          Value: sn-dmz-A
  SubnetDMZB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref QAVPC
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      CidrBlock: 10.21.112.0/20
      Tags:
        - Key: Name
          Value: sn-dmz-B
  SubnetDMZC:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref QAVPC
      AvailabilityZone: !Select [ 2, !GetAZs '' ]
      CidrBlock: 10.21.176.0/20
      Tags:
        - Key: Name
          Value: sn-dmz-C

  # PROD Subnets
  SubnetFIMA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref PRODVPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: 10.22.0.0/20
      Tags:
        - Key: Name
          Value: sn-fim-A
  SubnetFIMB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref PRODVPC
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      CidrBlock: 10.22.64.0/20
      Tags:
        - Key: Name
          Value: sn-fim-B
  SubnetFIMC:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref PRODVPC
      AvailabilityZone: !Select [ 2, !GetAZs '' ]
      CidrBlock: 10.22.128.0/20
      Tags:
        - Key: Name
          Value: sn-fim-C
  SubnetSIEMA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref PRODVPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: 10.22.16.0/20
      Tags:
        - Key: Name
          Value: sn-siem-A
  SubnetSIEMB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref PRODVPC
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      CidrBlock: 10.22.80.0/20
      Tags:
        - Key: Name
          Value: sn-siem-B
  SubnetSIEMC:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref PRODVPC
      AvailabilityZone: !Select [ 2, !GetAZs '' ]
      CidrBlock: 10.22.144.0/20
      Tags:
        - Key: Name
          Value: sn-siem-C
  SubnetNFTAA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref PRODVPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: 10.22.32.0/20
      Tags:
        - Key: Name
          Value: sn-nfta-A
  SubnetNFTAB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref PRODVPC
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      CidrBlock: 10.22.96.0/20
      Tags:
        - Key: Name
          Value: sn-nfta-B
  SubnetNFTAC:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref PRODVPC
      AvailabilityZone: !Select [ 2, !GetAZs '' ]
      CidrBlock: 10.22.160.0/20
      Tags:
        - Key: Name
          Value: sn-nfta-C
  SubnetDMZA:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref PRODVPC
      AvailabilityZone: !Select [ 0, !GetAZs '' ]
      CidrBlock: 10.22.48.0/20
      Tags:
        - Key: Name
          Value: sn-dmz-A
  SubnetDMZB:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref PRODVPC
      AvailabilityZone: !Select [ 1, !GetAZs '' ]
      CidrBlock: 10.22.112.0/20
      Tags:
        - Key: Name
          Value: sn-dmz-B
  SubnetDMZC:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref PRODVPC
      AvailabilityZone: !Select [ 2, !GetAZs '' ]
      CidrBlock: 10.22.176.0/20
      Tags:
        - Key: Name
          Value: sn-dmz-C
